#!/bin/bash

# Termux Alist Guide - Auto Setup Script

echo -e "\033[1;32m正在启动 Termux Alist 向导安装程序...\033[0m"

# 1. Update Termux repositories
echo "正在更新软件包列表..."
pkg update -y

# 2. Install Node.js LTS if not present
if ! command -v node &> /dev/null; then
    echo "正在安装 Node.js..."
    pkg install nodejs-lts -y
else
    echo "Node.js 已安装。"
fi

# 3. Install dependencies
if [ -f "package.json" ]; then
    echo "正在安装项目依赖 (这可能需要几分钟)..."
    npm install
else
    echo -e "\033[1;31m错误: 未找到 package.json。请确保你在正确的目录下。\033[0m"
    exit 1
fi

# 4. Configure Bot Variables
echo -e "\n\033[1;34m--- 机器人配置 (可选) ---\033[0m"
echo "为了方便你复制脚本，请输入你的 Telegram Bot 信息。"
echo "这些信息将自动填入网页中的 Python 代码块。"
echo "如果不想配置，请直接按回车跳过。"

read -p "请输入 Bot Token: " bot_token
read -p "请输入管理员 Telegram ID (数字ID): " admin_id

# Create or overwrite .env file
echo "# Generated by setup.sh" > .env
if [ ! -z "$bot_token" ]; then
    echo "VITE_BOT_TOKEN=$bot_token" >> .env
fi
if [ ! -z "$admin_id" ]; then
    echo "VITE_ADMIN_ID=$admin_id" >> .env
fi

echo -e "\033[1;32m配置已保存！\033[0m"

# 5. Start the application
echo -e "\033[1;32m安装完成！正在启动应用...\033[0m"
echo "应用稍后将在浏览器中打开： http://localhost:5173"
npm run dev -- --host