#!/bin/bash

# Termux Alist Guide - Auto Setup Script

echo -e "\033[1;32m正在启动 Termux Alist 向导 CLI...\033[0m"

# 1. Update Termux repositories
echo "正在更新软件包列表..."
pkg update -y

# 2. Install Node.js LTS if not present
if ! command -v node &> /dev/null; then
    echo "正在安装 Node.js..."
    pkg install nodejs-lts -y
else
    echo "Node.js 已安装。"
fi

# 3. Install dependencies
if [ -f "package.json" ]; then
    echo "正在安装项目依赖..."
    
    # Force update package.json if it contains the wrong start script or dependency
    if grep -q "dist/main.js" package.json || grep -q "0.1.3" package.json; then
        echo "检测到旧版配置文件，正在修复..."
        cat > package.json << 'EOF'
{
  "name": "termux-alist-guide",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "lint": "eslint . --report-unused-disable-directives --max-warnings 0",
    "start": "tsx src/main.ts"
  },
  "dependencies": {
    "@google/genai": "*",
    "tsx": "^4.19.0",
    "typescript": "^5.5.0"
  },
  "devDependencies": {
    "@eslint/js": "^10.0.1",
    "@types/node": "^22.0.0",
    "eslint": "^10.0.0",
    "globals": "^17.3.0",
    "typescript-eslint": "^8.0.0"
  }
}
EOF
    fi

    # Remove node_modules and package-lock.json to ensure clean install if previous failed
    if [ -d "node_modules" ]; then
        echo "清理旧依赖..."
        rm -rf node_modules package-lock.json
    fi
    npm install
else
    echo -e "\033[1;31m错误: 未找到 package.json。请确保你在正确的目录下。\033[0m"
    exit 1
fi

# 4. Configure Bot Variables
if [ -f ".env" ]; then
    echo -e "\n\033[1;33m检测到 .env 文件已存在，跳过配置。\033[0m"
else
    echo -e "\n\033[1;34m--- 机器人配置 (可选) ---\033[0m"
    echo "为了方便你复制脚本，请输入你的 Telegram Bot 信息。"
    echo "这些信息将自动填入 CLI 生成的代码块中。"
    echo "如果不想配置，请直接按回车跳过。"

    read -p "请输入 Bot Token: " bot_token
    read -p "请输入管理员 Telegram ID (数字ID): " admin_id

    # Create .env file
    echo "# Generated by setup.sh" > .env
    # 如果存在系统环境变量 API_KEY，也写入 .env 以便 CLI 读取
    if [ ! -z "$API_KEY" ]; then
        echo "API_KEY=$API_KEY" >> .env
    fi
    if [ ! -z "$bot_token" ]; then
        echo "BOT_TOKEN=$bot_token" >> .env
    fi
    if [ ! -z "$admin_id" ]; then
        echo "ADMIN_ID=$admin_id" >> .env
    fi
    echo -e "\033[1;32m配置已保存！\033[0m"
fi

# 5. Start the Auto Install
echo -e "\033[1;32m正在启动全自动安装流程...\033[0m"
# Use npx tsx to run the install script directly
./node_modules/.bin/tsx src/install.ts